name: Lint Go

on:
  push:
    branches:
      - develop
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.5'      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v3.3.1
          github-token: ${{secrets.test_token}}