name: Test

on: 
  push:
    branches:
      - develop
      - main

jobs:
  test: 
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x, 1.19.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Test
        run: go test ./..